Repository jobda-keychain/keychain, pull requests merged in 2022-01, with the labels that each got.

#9 User Update
  src/main/java/com/jobda/keychain/controller/UserController.java
  src/main/java/com/jobda/keychain/entity/User.java
  src/main/java/com/jobda/keychain/request/UpdateUserRequest.java
  src/main/java/com/jobda/keychain/service/UserService.java
Labels: feature

#26 (#22) AccountEnvironment 엔티티 추가
  src/main/java/com/jobda/keychain/entity/account/Account.java
  src/main/java/com/jobda/keychain/entity/account/repository/AccountRepository.java
  src/main/java/com/jobda/keychain/entity/account_environment/AccountEnvironment.java
  src/main/java/com/jobda/keychain/entity/account_environment/repository/AccountEnvironmentRepository.java
  src/main/java/com/jobda/keychain/entity/environment/Environment.java
Labels: setting

#25 (#20) Environment 엔티티 추가
  src/main/java/com/jobda/keychain/entity/account/Account.java
  src/main/java/com/jobda/keychain/entity/account/Service.java
  src/main/java/com/jobda/keychain/entity/account/repository/AccountRepository.java
  src/main/java/com/jobda/keychain/entity/account_environment/AccountEnvironment.java
  src/main/java/com/jobda/keychain/entity/account_environment/repository/AccountEnvironmentRepository.java
  src/main/java/com/jobda/keychain/entity/environment/Environment.java
  src/main/java/com/jobda/keychain/entity/environment/repository/EnvironmentRepository.java
Labels: setting

#32 [ADD] (#30) Github Action 추가
  .github/workflows/gradle.yml
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  src/main/java/com/jobda/keychain/controller/UserController.java
  src/main/java/com/jobda/keychain/service/UserService.java
Labels: setting

#29 (#28) 엔티티 코드 피드백 반영
  src/main/java/com/jobda/keychain/entity/account/Account.java
  src/main/java/com/jobda/keychain/entity/account/ServiceType.java
  src/main/java/com/jobda/keychain/entity/account_environment/AccountEnvironment.java
  src/main/java/com/jobda/keychain/entity/account_environment/repository/AccountEnvironmentRepository.java
  src/main/java/com/jobda/keychain/entity/environment/Environment.java
  src/main/java/com/jobda/keychain/entity/environment/repository/EnvironmentRepository.java
  src/main/java/com/jobda/keychain/service/UserService.java
Labels: setting

#41 (#39) 서비스 엔티티 추가
  src/main/java/com/jobda/keychain/entity/environment/Environment.java
  src/main/java/com/jobda/keychain/entity/platform/Platform.java
  src/main/java/com/jobda/keychain/entity/platform/repository/PlatformRepository.java
Labels: setting

#43 (#42) 서버 도메인, 클라이언트 도메인 칼럼 추가
  src/main/java/com/jobda/keychain/entity/account/Account.java
  src/main/java/com/jobda/keychain/entity/environment/Environment.java
  src/main/java/com/jobda/keychain/entity/platform/Platform.java
  src/main/java/com/jobda/keychain/entity/platform/ServiceType.java
Labels: setting

#33 (#31) CORS 설정
  src/main/java/com/jobda/keychain/config/WebConfig.java
Labels: setting

#47 (#46) setting exception
  src/main/java/com/jobda/keychain/exception/UserNotFoundException.java
  src/main/java/com/jobda/keychain/exception/handler/ErrorResponse.java
  src/main/java/com/jobda/keychain/exception/handler/KeyChainException.java
  src/main/java/com/jobda/keychain/exception/handler/KeyChainExceptionFilter.java
  src/main/java/com/jobda/keychain/exception/handler/KeyChainExceptionHandler.java
Labels: setting

#56 (#55) 프로젝트 설정 추가
  .gitignore
  build.gradle
  src/main/java/com/jobda/keychain/controller/EnvironmentController.java
  src/main/java/com/jobda/keychain/controller/UserController.java
  src/main/java/com/jobda/keychain/dto/request/CreateUserRequest.java
  src/main/java/com/jobda/keychain/dto/request/UpdateUserRequest.java
  src/main/java/com/jobda/keychain/dto/response/Test.java
  src/main/java/com/jobda/keychain/service/EnvironmentService.java
  src/main/java/com/jobda/keychain/service/UserService.java
Labels: setting

#57 (#55) 충돌 줄이기 위해 미리 pull 받아 놓기
  .gitignore
  build.gradle
  src/main/java/com/jobda/keychain/controller/EnvironmentController.java
  src/main/java/com/jobda/keychain/dto/response/Test.java
  src/main/java/com/jobda/keychain/service/EnvironmentService.java
Labels: setting

#60 [ADD] (#53) 외부 로그인 api 호출 메소드 만들기
  build.gradle
  src/main/java/com/jobda/keychain/AuthApiClient.java
  src/main/java/com/jobda/keychain/KeychainApplication.java
  src/main/java/com/jobda/keychain/dto/request/LoginApiRequest.java
  src/main/java/com/jobda/keychain/dto/response/LoginApiResponse.java
  src/main/java/com/jobda/keychain/exception/UnableLoginException.java
  src/main/java/com/jobda/keychain/service/UserService.java
Labels: feature

#61 (#44) 환경 추가 api
  src/main/java/com/jobda/keychain/controller/EnvironmentController.java
  src/main/java/com/jobda/keychain/dto/request/AddEnvironmentRequest.java
  src/main/java/com/jobda/keychain/entity/environment/Environment.java
  src/main/java/com/jobda/keychain/entity/environment/repository/EnvironmentRepository.java
  src/main/java/com/jobda/keychain/entity/platform/repository/PlatformRepository.java
  src/main/java/com/jobda/keychain/exception/AlreadyDataExistsException.java
  src/main/java/com/jobda/keychain/exception/DataNotFoundException.java
  src/main/java/com/jobda/keychain/exception/UserNotFoundException.java
  src/main/java/com/jobda/keychain/service/EnvironmentService.java
  src/test/java/com/jobda/keychain/controller/EnvironmentControllerTest.java
  src/test/java/com/jobda/keychain/service/EnvironmentServiceTest.java
Labels: feature

#63 (#36) 서비스에 대한 환경 조회
  .github/workflows/gradle.yml
  src/main/java/com/jobda/keychain/controller/EnvironmentController.java
  src/main/java/com/jobda/keychain/dto/response/PlatformEnvironmentsResponse.java
  src/main/java/com/jobda/keychain/dto/response/Test.java
  src/main/java/com/jobda/keychain/entity/platform/Platform.java
  src/main/java/com/jobda/keychain/exception/handler/KeyChainExceptionAdvice.java
  src/main/java/com/jobda/keychain/service/EnvironmentService.java
  src/test/java/com/jobda/keychain/controller/EnvironmentControllerTest.java
Labels: feature

#62 [ADD] (#1) 계정 추가 기능
  build.gradle
  src/main/java/com/jobda/keychain/controller/UserController.java
  src/main/java/com/jobda/keychain/dto/request/CreateAccountRequest.java
  src/main/java/com/jobda/keychain/dto/request/CreateUserRequest.java
  src/main/java/com/jobda/keychain/entity/account/Account.java
  src/main/java/com/jobda/keychain/exception/handler/KeyChainExceptionAdvice.java
  src/main/java/com/jobda/keychain/service/UserService.java
Labels: feature

#66 (#3) 계정 정보 수정 개발
  src/main/java/com/jobda/keychain/controller/UserController.java
  src/main/java/com/jobda/keychain/dto/request/UpdateAccountRequest.java
  src/main/java/com/jobda/keychain/dto/request/UpdateUserRequest.java
  src/main/java/com/jobda/keychain/dto/response/UpdateAccountResponse.java
  src/main/java/com/jobda/keychain/entity/account/Account.java
  src/main/java/com/jobda/keychain/service/UserService.java
Labels: feature

#70 (#40) 자동 로그인
  src/main/java/com/jobda/keychain/controller/UserController.java
  src/main/java/com/jobda/keychain/dto/response/TokenResponse.java
  src/main/java/com/jobda/keychain/service/UserService.java
Labels: feature

#77 (#76) Swagger 설정
  build.gradle
  src/main/java/com/jobda/keychain/config/SwaggerConfig.java
Labels: setting

#78 (#64) Account의 description field에 not null 설정
  src/main/java/com/jobda/keychain/dto/request/CreateAccountRequest.java
  src/main/java/com/jobda/keychain/dto/request/UpdateAccountRequest.java
  src/main/java/com/jobda/keychain/entity/account/Account.java
Labels: feature

#68 (#51) 환경 목록 api
  build.gradle
  src/main/java/com/jobda/keychain/config/QuerydslConfig.java
  src/main/java/com/jobda/keychain/controller/EnvironmentController.java
  src/main/java/com/jobda/keychain/dto/response/EnvironmentsResponse.java
  src/main/java/com/jobda/keychain/entity/environment/repository/EnvironmentRepository.java
  src/main/java/com/jobda/keychain/entity/environment/repository/EnvironmentRepositoryExtension.java
  src/main/java/com/jobda/keychain/entity/environment/repository/EnvironmentRepositoryImpl.java
  src/main/java/com/jobda/keychain/service/EnvironmentService.java
  src/test/java/com/jobda/keychain/controller/EnvironmentControllerTest.java
Labels: feature

#49 (#4) 유저 삭제 기능 수정
  gradlew
  src/main/java/com/jobda/keychain/controller/UserController.java
  src/main/java/com/jobda/keychain/service/UserService.java
Labels: feature

#72 (#2) 회원 조회 페이징 및 필터링
  build.gradle
  src/main/java/com/jobda/keychain/config/QuerydslConfig.java
  src/main/java/com/jobda/keychain/config/WebConfig.java
  src/main/java/com/jobda/keychain/controller/UserController.java
  src/main/java/com/jobda/keychain/dto/request/CreateUserRequest.java
  src/main/java/com/jobda/keychain/dto/request/UpdateUserRequest.java
  src/main/java/com/jobda/keychain/dto/response/SelectUserDto.java
  src/main/java/com/jobda/keychain/dto/response/SelectUserResponse.java
  src/main/java/com/jobda/keychain/entity/platform/repository/PlatformRepository.java
  src/main/java/com/jobda/keychain/entity/platform/repository/PlatformRepositoryExtension.java
  src/main/java/com/jobda/keychain/entity/platform/repository/PlatformRepositoryImpl.java
  src/main/java/com/jobda/keychain/service/UserService.java
  src/main/resources/application.yml
  src/main/resources/data.sql
  src/main/resources/table.sql
  src/test/java/com/jobda/keychain/controller/EnvironmentControllerTest.java
Labels: feature

#73 (#71) 환경 조회 - platform 키워드 nullable
  src/main/java/com/jobda/keychain/controller/EnvironmentController.java
  src/main/java/com/jobda/keychain/dto/response/PlatformEnvironmentsResponse.java
  src/main/java/com/jobda/keychain/entity/environment/repository/EnvironmentRepositoryExtension.java
  src/main/java/com/jobda/keychain/entity/environment/repository/EnvironmentRepositoryImpl.java
  src/main/java/com/jobda/keychain/service/EnvironmentService.java
  src/test/java/com/jobda/keychain/controller/EnvironmentControllerTest.java
Labels: feature

#83 (#79) 코드 리팩토링
  src/main/java/com/jobda/keychain/config/QuerydslConfig.java
  src/main/java/com/jobda/keychain/config/WebConfig.java
  src/main/java/com/jobda/keychain/controller/UserController.java
  src/main/java/com/jobda/keychain/dto/request/CreateAccountRequest.java
  src/main/java/com/jobda/keychain/dto/request/CreateUserRequest.java
  src/main/java/com/jobda/keychain/dto/request/LoginApiRequest.java
  src/main/java/com/jobda/keychain/dto/request/UpdateAccountRequest.java
  src/main/java/com/jobda/keychain/dto/request/UpdateUserRequest.java
  src/main/java/com/jobda/keychain/dto/response/DetailsResponse.java
  src/main/java/com/jobda/keychain/dto/response/LoginApiResponse.java
  src/main/java/com/jobda/keychain/dto/response/PlatformEnvironmentsResponse.java
  src/main/java/com/jobda/keychain/dto/response/SelectUserDto.java
  src/main/java/com/jobda/keychain/dto/response/TokenResponse.java
  src/main/java/com/jobda/keychain/dto/response/UpdateAccountResponse.java
  src/main/java/com/jobda/keychain/entity/account/Account.java
  src/main/java/com/jobda/keychain/entity/account/repository/AccountRepository.java
  src/main/java/com/jobda/keychain/entity/environment/repository/EnvironmentRepository.java
  src/main/java/com/jobda/keychain/entity/platform/repository/PlatformRepository.java
  src/main/java/com/jobda/keychain/entity/platform/repository/PlatformRepositoryExtension.java
  src/main/java/com/jobda/keychain/entity/platform/repository/PlatformRepositoryImpl.java
  src/main/java/com/jobda/keychain/service/EnvironmentService.java
  src/main/java/com/jobda/keychain/service/UserService.java
Labels: refactoring

#85 (#79) 코드 리팩토링
  src/main/java/com/jobda/keychain/dto/response/EnvironmentsResponse.java
  src/main/java/com/jobda/keychain/dto/response/PlatformEnvironmentsResponse.java
  src/main/java/com/jobda/keychain/service/EnvironmentService.java
  src/test/java/com/jobda/keychain/controller/EnvironmentControllerTest.java
  src/test/resources/application-test.properties
Labels: refactoring

#87 (#86) 계정 조회 및 상세 조회 코드 리팩토링
  src/main/java/com/jobda/keychain/dto/response/DetailsResponse.java
  src/main/java/com/jobda/keychain/dto/response/SelectUserDto.java
  src/main/java/com/jobda/keychain/dto/response/SelectUserResponse.java
  src/main/java/com/jobda/keychain/entity/platform/repository/PlatformRepositoryExtension.java
  src/main/java/com/jobda/keychain/entity/platform/repository/PlatformRepositoryImpl.java
  src/main/java/com/jobda/keychain/service/UserService.java
Labels: refactoring

#84 (#82) account refactor
  src/main/java/com/jobda/keychain/dto/response/UpdateAccountResponse.java
  src/main/java/com/jobda/keychain/service/UserService.java
Labels: refactoring

#106 (#103) [UPDATE] Swagger Property Setting
  src/main/java/com/jobda/keychain/config/SwaggerConfig.java
  src/main/java/com/jobda/keychain/config/WebConfig.java
Labels: docs

#97 (#52) mysql db 연결
  build.gradle
  key-chain.sql
  src/main/java/com/jobda/keychain/controller/EnvironmentController.java
  src/main/java/com/jobda/keychain/controller/UserController.java
  src/main/java/com/jobda/keychain/dto/request/AddEnvironmentRequest.java
  src/main/java/com/jobda/keychain/dto/response/DetailsResponse.java
  src/main/java/com/jobda/keychain/dto/response/EnvironmentsResponse.java
  src/main/java/com/jobda/keychain/dto/response/PlatformEnvironmentsResponse.java
  src/main/java/com/jobda/keychain/dto/response/SelectUserDto.java
  src/main/java/com/jobda/keychain/dto/response/UpdateAccountResponse.java
  src/main/java/com/jobda/keychain/entity/environment/repository/EnvironmentRepositoryExtension.java
  src/main/java/com/jobda/keychain/entity/environment/repository/EnvironmentRepositoryImpl.java
  src/main/java/com/jobda/keychain/entity/platform/Platform.java
  src/main/java/com/jobda/keychain/entity/platform/PlatformType.java
  src/main/java/com/jobda/keychain/entity/platform/repository/PlatformRepository.java
  src/main/java/com/jobda/keychain/entity/platform/repository/PlatformRepositoryExtension.java
  src/main/java/com/jobda/keychain/entity/platform/repository/PlatformRepositoryImpl.java
  src/main/java/com/jobda/keychain/service/EnvironmentService.java
  src/main/java/com/jobda/keychain/service/UserService.java
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
  src/test/java/com/jobda/keychain/controller/EnvironmentControllerTest.java
  src/test/java/com/jobda/keychain/service/EnvironmentServiceTest.java
  src/test/resources/application-test.properties
  src/test/resources/application.yml
  src/test/resources/data.sql
  src/test/resources/table.sql
Labels: setting

#107 (#81) account api docs
  src/main/java/com/jobda/keychain/controller/UserController.java
  src/main/java/com/jobda/keychain/dto/request/CreateAccountRequest.java
  src/main/java/com/jobda/keychain/dto/request/UpdateAccountRequest.java
Labels: docs

#118 [UPDATE] (#116) h2로 서버 구동시키기
  build.gradle
  src/main/resources/application.yml
  src/main/resources/data.sql
  src/main/resources/table.sql
Labels: setting

#115 (#93) Migration Swagger Annotation
  src/main/java/com/jobda/keychain/controller/UserController.java
  src/main/java/com/jobda/keychain/dto/request/CreateAccountRequest.java
  src/main/java/com/jobda/keychain/dto/request/UpdateAccountRequest.java
Labels: docs

#124 (#123) 파일 포맷 war에서 jar로 변경
  build.gradle
Labels: setting

#130 (#129) 환경 수정 api 테스트코드 추가
  src/main/java/com/jobda/keychain/controller/EnvironmentController.java
  src/main/java/com/jobda/keychain/dto/request/UpdateEnvironmentRequest.java
  src/test/java/com/jobda/keychain/controller/EnvironmentControllerTest.java
Labels: test

#114 (#91) 환경 관련 api swagger 추가
  src/main/java/com/jobda/keychain/controller/EnvironmentController.java
  src/main/java/com/jobda/keychain/controller/UserController.java
  src/main/java/com/jobda/keychain/dto/request/AddEnvironmentRequest.java
  src/main/java/com/jobda/keychain/dto/request/UpdateEnvironmentRequest.java
Labels: docs

#131 (#99) 계정 조회, 상세 조회, 삭제 스웨거 추가
  src/main/java/com/jobda/keychain/controller/UserController.java
Labels: docs

#128 (#112) 계정 조회 시 totalPages 수정 및 environment id 리스트가 빈 리스트일 시 null로 체크
  src/main/java/com/jobda/keychain/entity/platform/repository/PlatformRepositoryImpl.java
Labels: bug

#136 [FIX] (#134) Update Response Model
  src/main/java/com/jobda/keychain/dto/response/TokenResponse.java
  src/main/java/com/jobda/keychain/service/UserService.java
Labels: feature

#132 (#117) 메일 전송
  build.gradle
  src/main/java/com/jobda/keychain/AuthApiClient.java
  src/main/java/com/jobda/keychain/KeychainApplication.java
  src/main/java/com/jobda/keychain/config/AsyncConfig.java
  src/main/java/com/jobda/keychain/config/FeignConfiguration.java
  src/main/java/com/jobda/keychain/dto/response/JobdaAccountInfoResponse.java
  src/main/java/com/jobda/keychain/service/MailService.java
  src/main/java/com/jobda/keychain/service/UserService.java
  src/main/resources/application.yml
  src/test/resources/application.yml
Labels: feature

#156 (#147) 환경 목록에 필터링 추가
  src/main/java/com/jobda/keychain/controller/EnvironmentController.java
  src/main/java/com/jobda/keychain/entity/environment/repository/EnvironmentRepositoryExtension.java
  src/main/java/com/jobda/keychain/entity/environment/repository/EnvironmentRepositoryImpl.java
  src/main/java/com/jobda/keychain/service/EnvironmentService.java
Labels: bug

#153 (#146) codecov 측정을 위한 세팅
  .github/workflows/gradle.yml
  build.gradle
Labels: test

#144 (#98) 계정 조회, 상세 조회, 삭제 테스트 코드 작성
  src/test/java/com/jobda/keychain/controller/AccountControllerTest.java
  src/test/resources/data.sql
Labels: test

#160 Hotfix 3.0.3
  src/main/java/com/jobda/keychain/controller/EnvironmentController.java
  src/main/java/com/jobda/keychain/entity/environment/repository/EnvironmentRepositoryExtension.java
  src/main/java/com/jobda/keychain/entity/environment/repository/EnvironmentRepositoryImpl.java
  src/main/java/com/jobda/keychain/service/EnvironmentService.java
Labels: bug

#171 (#169) fix codecov
  .github/workflows/gradle.yml
  build.gradle
Labels: bug

#175 (#173) db에 레코드 추가 시간, 수정 시간 컬럼 추가
  src/main/java/com/jobda/keychain/entity/BaseLastModifiedAtEntity.java
  src/main/java/com/jobda/keychain/entity/account/Account.java
  src/main/java/com/jobda/keychain/entity/environment/Environment.java
  src/main/resources/table.sql
  src/test/resources/table.sql
Labels: setting, database

#170 (#168) 상세 정보 response에 환경 정보 수정
  src/main/java/com/jobda/keychain/dto/response/DetailsAccountEnvironmentDto.java
  src/main/java/com/jobda/keychain/dto/response/DetailsResponse.java
Labels: feature

#166 (#164) 계정 조회 최신순으로 정렬
  src/main/java/com/jobda/keychain/entity/platform/repository/PlatformRepositoryImpl.java
Labels: feature

#167 (#162) 환경 정보 아무것도 바꾸지 않았을 때 409 나는 것 고치기
  src/main/java/com/jobda/keychain/entity/environment/repository/EnvironmentRepository.java
  src/main/java/com/jobda/keychain/service/EnvironmentService.java
  src/test/java/com/jobda/keychain/controller/EnvironmentControllerTest.java
  src/test/resources/data.sql
Labels: bug

#172 (#163) h2 profile 삭제
  src/main/resources/application-h2.yml
  src/main/resources/application.yml
Labels: setting

#157 (#139) 로그 저장 메소드 컨트롤러 단에 추가
  src/main/java/com/jobda/keychain/controller/EnvironmentController.java
  src/main/java/com/jobda/keychain/controller/UserController.java
  src/main/java/com/jobda/keychain/event/LogEvent.java
  src/main/java/com/jobda/keychain/event/handler/LogEventHandler.java
  src/main/java/com/jobda/keychain/service/EnvironmentService.java
  src/main/java/com/jobda/keychain/service/LogService.java
  src/main/java/com/jobda/keychain/service/UserService.java
  src/main/java/com/jobda/keychain/utils/LogUtil.java
  src/test/resources/table.sql
Labels: feature

#165 (#45) test code
  src/main/java/com/jobda/keychain/dto/request/CreateAccountRequest.java
  src/main/java/com/jobda/keychain/dto/request/UpdateAccountRequest.java
  src/main/java/com/jobda/keychain/entity/account/repository/AccountRepository.java
  src/main/java/com/jobda/keychain/service/UserService.java
  src/test/java/com/jobda/keychain/controller/UserControllerTest.java
  src/test/resources/data.sql
  src/test/resources/table.sql
Labels: test

#183 (#182) 이벤트 핸들러 사용법 수정
  src/main/java/com/jobda/keychain/event/handler/LogEventHandler.java
  src/main/java/com/jobda/keychain/service/AccountService.java
  src/main/java/com/jobda/keychain/service/EnvironmentService.java
Labels: feature

#195 (#193) 유저, 환경 정렬방법 변경
  src/main/java/com/jobda/keychain/entity/environment/repository/EnvironmentRepositoryImpl.java
  src/main/java/com/jobda/keychain/entity/platform/repository/PlatformRepositoryImpl.java
Labels: feature

#200 (#197) 계정 추가의 환경 목록과 필터링할 때 환경 목록 api 분리하기
  src/main/java/com/jobda/keychain/controller/EnvironmentController.java
  src/main/java/com/jobda/keychain/dto/response/EnvironmentNamesResponse.java
  src/main/java/com/jobda/keychain/dto/response/PlatformEnvironmentsResponse.java
  src/main/java/com/jobda/keychain/entity/environment/repository/EnvironmentRepositoryExtension.java
  src/main/java/com/jobda/keychain/entity/environment/repository/EnvironmentRepositoryImpl.java
  src/main/java/com/jobda/keychain/service/EnvironmentService.java
  src/test/java/com/jobda/keychain/controller/EnvironmentControllerTest.java
Labels: feature

#196 (#194) exception advisor에 디버깅을 위한 에러메시지 출력 추가
  src/main/java/com/jobda/keychain/exception/handler/KeyChainExceptionAdvice.java
  src/test/java/com/jobda/keychain/controller/EnvironmentControllerTest.java
Labels: setting

#201 (#180) test 커버리지 올리기
  src/main/java/com/jobda/keychain/entity/account/repository/AccountRepository.java
  src/main/java/com/jobda/keychain/service/AccountService.java
  src/test/java/com/jobda/keychain/controller/AccountControllerTest.java
  src/test/java/com/jobda/keychain/controller/EnvironmentControllerTest.java
  src/test/java/com/jobda/keychain/controller/UserControllerTest.java
  src/test/java/com/jobda/keychain/service/LogServiceTest.java
  src/test/java/com/jobda/keychain/service/MailServiceTest.java
  src/test/resources/data.sql
Labels: test

#219 (#213) 메일 정보
  src/main/resources/application.yml
Labels: feature

#220 (#217) 공백 막기
  src/main/java/com/jobda/keychain/dto/request/AddEnvironmentRequest.java
  src/main/java/com/jobda/keychain/dto/request/CreateAccountRequest.java
  src/main/java/com/jobda/keychain/dto/request/UpdateAccountRequest.java
  src/main/java/com/jobda/keychain/dto/request/UpdateEnvironmentRequest.java
  src/main/java/com/jobda/keychain/service/AccountService.java
  src/main/java/com/jobda/keychain/service/EnvironmentService.java
  src/test/java/com/jobda/keychain/controller/AccountControllerTest.java
  src/test/java/com/jobda/keychain/controller/EnvironmentControllerTest.java
Labels: bug

#202 (#198) Domain Check Method
  src/main/java/com/jobda/keychain/AuthApiClient.java
  src/main/java/com/jobda/keychain/service/AccountService.java
Labels: feature

#222 (#221) 로그 저장 오류 고치기
  src/main/java/com/jobda/keychain/event/handler/LogEventHandler.java
Labels: bug
